### ISSUE TITLE
Image improvements

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#263]
from @thetwopct :
**Add new image sizes**
Use add_image_size to create scaled image sizes for different thumb versions. 
I.e Featured Speaker images could have 120x120, 140x140, 180x180, 220x220, so then the srcset will load the correct one depending on the users device screen size.

**Stop using CSS background images, pull in to page, use srcset**
Pull in background images using get_attachment_image, use object-fit cover instead of using background images, specify a thumbnail size for best fit. Numerous benefits; responsive scaled images for mobile users, better accessibility, no hard coded links in CSS.

**Use scaled background images using srcset**
If using object-fit is not possible for some reason, can still serve scaled images by using inline media queries and different breakpoints per srcset image.

**Comment by thetwopct** [comment]
OK been spending some decent time on the site today. I've moved the hero image on singular.php to srcset and object fit, and set up a few CSS commands that can be/should be able to be re-used for other places should they need it.

Other areas to look at:

**Front page image slider**
Switch this to inline media queries using srcset so the animation and effects are retained.

**Speakers block** 
Convert to img srcset / object fit cover instead of background image. Was background-image only used here so the image was a bit more responsive or am I missing something? 

**Text on image block**
Convert to img srcset / object fit cover instead of background image. I had a quick play with this and tried to rebuild the block, for some reason not updating. 

**UGB Container block**
This block is being used for the Events page hero, this only loads one image via CSS background-image.  Unless we move away from the UGB Container Block, using srcset for this is not possible. 
This issue claims to be fixed in V2 of the plugin, but this isn't released yet. And this may only be thumbnail size selection, rather than scaled srcset images. https://github.com/gambitph/Stackable/issues/59
Could remake the block.

**Comment by cjyabraham** [comment]
@andycochran can you weigh in on the above points?

**Comment by cjyabraham** [comment]
@thetwopct which of the above ideas have not been implemented?  I'll break them into a new issue and close this one out.

**Comment by thetwopct** [comment]
They are all outstanding.

Frontpage slider - I would retain the images inserted via CSS, but move the CSS in to the page and generate CSS media queries using srcset. Here's a snippet that should just drop in and point you in the right direction - https://gist.github.com/thetwopct/bc43a0980ebd094c76f7781f5d67d78d

Speakers Block - Ideally needs the image srcset code copied from singular.php https://github.com/LF-Engineering/lfevents/blob/7af5c1de8a7371abd5bccc901f613e4cc20a67f8/web/wp-content/themes/lfevents/singular.php#L97 unless there was a reason for doing them as background images in the first place? 

Text on image block - can use the same snippet as above, for some reason I couldn't get this block updating when I tried to edit locally.

UGB - wait for V2 of plugin or try to recreate it the block. I don't think V2 will be using srcset, and as the hero of every events page, it will impact first paint / speed scores as it is. So could be worth the time to do properly, and I think that could be the only UGB block used, so we could then lose that plugin completely.

**Comment by cjyabraham** [comment]
[Stackable v 2](https://wpstackable.com/blog/version-2-is-out/) is now out and contains the responsive image loading.

**Comment by cjyabraham** [comment]
I think much of the above is now either done or no longer relevant.  I'll close but @thetwopct if there's anything you'd like to preserve from this could you break into a new ticket?
