### ISSUE TITLE
Can't set full width for container block anymore

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#284]
We no longer seem to have the ability to make a container block fill the full width of the page.  We have an old one setup on [dev](https://dev-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=64&action=edit) but we no longer have that setting for any new container block.  Did you deactivate it at some point?

Does it have something to do with [this commit](https://github.com/LF-Engineering/lfevents/commit/54a8992a0fe6b1b4f90059d145f9521a0e48dcfd)?

**Comment by andycochran** [comment]
Ack! Yes. 😬 

We decided that we wanted the "wide" width to be the default. I'd though nixing `add_theme_support( 'align-wide' );` would just get rid of the wide option. I didn't realize it also gets rid of the full-width option. 

I see in the docs that it this theme support adds both the `alignwide` AND `alignfull` classes: 
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#wide-alignment

I'll work this back in. Tho I don't think we want to simply revert this commit, because we want the default width to be wider than they were.

**Comment by andycochran** [comment]
I've re-added the `.alignwide` option. There could be side effects to this, so I'm poking around to test. Please let me know if you notice anything weird.

**Comment by andycochran** [comment]
@cjyabraham, I think we can call this done, unless you've noticed any problems.
