### ISSUE TITLE
Improve design of code of conduct page

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#290]
@meganelizabethphillips is using containers for all the text on [this page](https://live-lfeventsci.pantheonsite.io/about/code-of-conduct/) but it is effectively giving a left and right margin such that it's not consistent with [other about pages](https://live-lfeventsci.pantheonsite.io/about/sponsor/) and doesn't use the width well especially in mobile.  She wanted to add some visual variety to the page by giving some paragraphs a background color so it wasn't one long page of text.  But, in doing that, she also had to have a margin on those paragraphs.  She thus put all text in containers to get the margins to match.

How can we make the page look good without having to have margins?

**Comment by andycochran** [comment]
Related to #284.

**Comment by andycochran** [comment]
In the fix for #284, I've adjusted the padding for align-wide blocks. This will need to be deployed to prod before we can fix the page you linked to above. But here's what I did locally that looks pretty good: 

- The first two paragraphs, I removed them from the container block. They're now just top-level blocks. 
- They're followed by a container block that's set to "Full Width." Since the content inside a full-width container will fill its width, inside it is another container block set to "Wide Width" which contains the header and paragraph.
- (the items below that I didn't change, so they're not aligned well)

![image](https://user-images.githubusercontent.com/409279/66261530-1afa3e00-e79d-11e9-946e-b98952d6fec0.png)

I also added styles so that container blocks that are set to "Short" will not have any top/bottom padding if they're are inside other container blocks. 

We can close this after we've updated the content on prod and confirm this is a good solution.

**Comment by cjyabraham** [comment]
Ok, I've updated [the page](https://live-lfeventsci.pantheonsite.io/about/code-of-conduct/) to match.  Looks pretty good (though I'm not entirely sold on the shaded blocks going full-width).

@meganelizabethphillips feel free to adjust things if you'd like.  I'll close this issue for now.

**Comment by andycochran** [comment]
They'd look better w/o the drop shadows.
