### ISSUE TITLE
Get text block color to take precedence over its container text color

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#347]
If you put a paragraph block inside a container, the text in the paragraph will take the container text color instead of the paragraph block text color.  Can this be fixed?

**Comment by andycochran** [comment]
This is because the Stackable Container block uses heavy-handed CSS that includes a `*` and multiple nested selectors that increase the specificity of its style rules, e.g.: 

```
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"], 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] *, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h1, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h2, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h3, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h4, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h5, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] h6, 
body:not(.wp-admin) .ugb-container[style*="--ugb-text-color"] p {
    color: var(--ugb-text-color);
}
```


They're more specific than our simple styles for the custom color palette, e.g.: 

```
.has-light-fuschia-color {
    color: #AD1457;
}
```

So our styles get overridden. 

An obvious solution would be to add `!important` to our custom palette styles in `...themes/lfevents/src/assets/scss/global/_custom-color-palette.scss`. But I'm hesitant to add important rules. It's not necessarily bad, but I'm not sure if this is just going to bring up other edge cases that want to have even more specificity/importance. 

Another solution is to clear the text color of the Stackable Container block and apply text colors each specific element within it. 

What's the use case here? Is there an specific design we're trying to fix?

**Comment by cjyabraham** [comment]
The use-case is the [Schedule at a glance block here](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/).  We want to make the text below the table white.  The weird thing is that, in the editor, it does appear white:

<img width="1016" alt="Screen Shot 2019-11-10 at 8 15 47 AM" src="https://user-images.githubusercontent.com/463160/68537147-58507d80-0392-11ea-8fa2-8bc1ce660b9e.png">

But the front-end isn't processing the styles in the same way.

Maybe we can find a workaround...

**Comment by cjyabraham** [comment]
@meganelizabethphillips , @andycochran advises that you don't set the text color on the container and instead only set it on the nested blocks.  So for this case, clear the color on the container and set it white for the paragraph.  Can you try that and let us know if that doesn't resolve this for you?

**Comment by meganelizabethphillips** [comment]
Hi all! I tried this today and it did not resolve this issue.

**Comment by cjyabraham** [comment]
I did it on the schedule at a glance block on [this page](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/).  I cleared the text color in the container and made sure the text color in the paragraph was set to white.  Where were you trying to do it @meganelizabethphillips ?
