### ISSUE TITLE
Format dates in registration block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#350]
[Registration block with both Chinese and English dates](https://www.lfasiallc.com/kubecon-cloudnativecon-china/register/) has the English ones going out of the cell and partially hidden.  Can we show each on its own line?

**Comment by cjyabraham** [comment]
I've made the dates appear on two lines however we need to expand the height of the container:
<img width="1032" alt="Screen Shot 2019-11-09 at 11 02 57 AM" src="https://user-images.githubusercontent.com/463160/68522689-aefd7f00-02e0-11ea-9ce0-b862548d1f2c.png">

I tried changing [this line](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/src/assets/scss/modules/_pricing-grid.scss#L166) to be `min-height` however the various headers ended up being different heights from each other at certain breakpoints.  So I'll leave it to you to style @andycochran .

**Comment by andycochran** [comment]
Oh. Hmm. This design assumes that there will only be two lines of text with an explicit height. In order for the column headers to be responsive (switching from being on each price's line on small screens to sticking out the top of the first tier's prices on large screens), the grid has an explicit top margin which allows for the column headers to be positioned absolute. Would it be acceptable to one use one date format instead of both translations? I'm not sure it'd be easy (or possible with this design) to make the column headers a fluid height. However, we could add styles that only apply to the China site.

**Comment by dankohn** [comment]
I think it's culturally-insensitive to use one date format for both Chinese and English. Could we just encode a 3 line solution for the Chinese site (maybe with a checkbox)?

**Comment by andycochran** [comment]
That's a great point, @dankohn. Thanks. We'll use styles that just target the China site.

**Comment by cjyabraham** [comment]
I have added the pantheon instance name as a class on the `<body>` tag, so on lfasiallc.com you can use `body.lfasiallcci ` for your css.

**Comment by cjyabraham** [comment]
Can you fix this for some of the narrower breakpoints as well:
<img width="802" alt="Screen Shot 2019-11-11 at 12 35 53 PM" src="https://user-images.githubusercontent.com/463160/68563352-d9d20980-047f-11ea-9806-553ff10355ed.png">

**Comment by cjyabraham** [comment]
from @andycochran : 
```
Chris, let’s add another line break between the tier name translations, so the headers will always be 4 lines. Then we can increase the height a bit more — change these to lines from 5.5 to 6.5: https://github.com/LF-Engineering/lfevents/commit/17230c9302ec01319123dfdd79cd5b276db3d78c#diff-60e930f671ed1995def26ed722b3e004R178-R181
```

**Comment by cjyabraham** [comment]
deployed
