### ISSUE TITLE
Alphabetize events

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#387]
Can you please change the listing on https://events.linuxfoundation.org/wp/wp-admin/admin.php?page=nestedpages to alphabetize events.

**Comment by cjyabraham** [comment]
This isn't easily done.  The nested pages plugin which produces [our default event listing](https://events.linuxfoundation.org/wp/wp-admin/admin.php?page=nestedpages) is designed to allow you to re-order pages manually by drag-and-drop and then it keeps the pages listed in the order you leave them in.  Automated ordering can be done in the [old view of pages](https://events.linuxfoundation.org/wp/wp-admin/edit.php?post_type=page&orderby=title&order=asc) however it's not very useful because it doesn't respect Event page hierarchy.  

@meganelizabethphillips has said that our current ordering doesn't really bother her so I'll file this as nice-to-have but feel free to push back @dankohn if there's a use-case for this we don't know about.

**Comment by cjyabraham** [comment]
Closing this as things are fine as is.
