### ISSUE TITLE
Image quality issues

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#491]
We now have a fairly complex image processing pipeline.  As an image gets processed, its quality degrades, and the final image that shows on our site is of lower quality than it should be.  Here's an example.  Open each image in a new tab to see how it degrades in quality.  Set your browser to 1440px wide to see what I'm seeing.

1. [Initial image is uploaded](https://dev-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-scaled-e1582058828530-1.jpg), 613KB.  Dimensions are 2560 × 1042.
2. [Scaled image is displayed on the site using srcset](https://dev-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-scaled-e1582058828530-1-1536x625.jpg), 267KB.  The scaled image is 1536x625 which is appropriate, given that my browser is 1440px wide.  Note this image looks significantly worse than 1.  Why?
3. [Scaled image is compressed using Shortpixel](https://dev-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-scaled-e1582058828530-1536x625.jpg), 142KB.  
4. [Webp image is generated by Shortpixel and served to Chrome and compatible browsers](https://dev-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-scaled-e1582058828530-1536x625.webp), 131KB.  Note the webp image is worse quality than its jpg-equivalent in 3.

How can we keep the quality of 1 while gaining some benefits from using a smaller image?

Here are some possible solutions:
1. [Stop WordPress from performing jpeg compression](https://www.wpbeginner.com/wp-tutorials/how-to-increase-or-decrease-wordpress-jpeg-image-compression/).  We could do this and just leave all compression to Shortpixel.
2. [Tinker with color profiles](https://wordpress.stackexchange.com/a/338732)

I've asked Shortpixel for their POV.  Also, @thetwopct, any thoughts?

**Comment by thetwopct** [comment]
I'm testing on a Retina Mac and HD Dell monitor and I don't think image 2 looks significantly bad at all - I would say more than adequate as a background image/header. I can read the small numbers in the top left, make out the Huawei logo on front of the stand bottom-right; certainly in line with what I would expect of reducing 40% of pixels from an image.

The scaled image generated at 2 is set via `big_image_size_threshold` - which is new command for WP that doesn't have a lot of options or finesse. [Reference](https://developer.wordpress.org/reference/hooks/big_image_size_threshold/).
Generates two new images:
```
1536×1536 (Custom, 1536×1536 pixel, not cropped)
2048×2048 (Custom, 2048×2048 pixel, not cropped)
```

The reference states "_The scaled down image will be used as the largest available size_" - so I assume that ShortPixel grabs this reduced size 80% compressed image as its source - then compressing it even more. So that is why subsequent images look worse.

Looking at ShortPixel options - LFE is current setup to use _Lossy_ compression type - which does tend to make images look worse, especially when starting from an already compressed starting point. I would typically choose _Glossy_ or _Lossless_.

Some other consideration is that WordPress srcset also has the `max_srcset_image_width` hook - which controls the limit of sizes introduced in to srcset and therefore what images large screen sizes view. I am pretty sure it set to 1600px wide max srcset (even though the [docs](https://developer.wordpress.org/reference/hooks/max_srcset_image_width/) say 2048px, I can't find reference to when it was changed). It can be controlled using something similar to this [thread](https://stackoverflow.com/questions/34210801/wordpress-4-4-change-max-srcset-image-width-in-media-php-from-functions-php ).

My recommendations would be to first change the compression settings in ShortPixel and see if that makes a difference to the end result. Unfortunately changing compression type requires all images to be re-processed, so we probably want to run a few tests on problem images away from the existing media library. 

If still issue remains, I would recommend turning off the `big_image_size_threshold` via WordPress hook `add_filter( 'big_image_size_threshold', __return_false);`  and then using ShortPixel to fully control large image resizing (under its "Resize large images" setting) and subsequent compression. This will remove the original image being compressed when ShortPixel compresses it.

There are other options and experiments to make, but above would be my starting point to solve the issue.

**Comment by cjyabraham** [comment]
I have implemented a fix that turns off all WP jpg compression.  Here are the resulting images:
1. [Initial image is uploaded](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/test1.jpg), 613KB. Dimensions are 2560 × 1042.
2. [Scaled image is displayed on the site using srcset](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/test1-1536x625.jpg), 1.1MB. This image is now a whopping 1.1MB but still looks just as bad as the version tested previously.
3. [Scaled image is compressed using Shortpixel](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/test1-1-1536x625.jpg), 168KB.
4. [Webp image is generated by Shortpixel and served to Chrome and compatible browsers](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/test1-1-1536x625.webp), 132KB. 

This basically shows that turning off the WP jpg compression doesn't seem to have done anything.  The big loss of quality is still between 1 and 2.

As a quick comparison, I used Preview to resize the original image manually to 1536x625 and [got this one](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/test1-1536px-by-preview.jpg), 297KB.  It looks a lot better than 2 above but not as good as 1.

**Comment by cjyabraham** [comment]
Shortpixel has a [Retina option](https://blog.shortpixel.com/how-to-use-optimized-retina-images-on-your-wordpress-site-for-best-user-experience-on-apple-devices/) which enables Retina double-density images to be created and delivered.  It requires the [WP Retina 2x](https://wordpress.org/plugins/wp-retina-2x/) plugin.  Maybe we should consider that.

**Comment by thetwopct** [comment]
The retina option just generates @2X size images which are then inserted via the retina plugin. Should not have any baring in this issue.

**Comment by cjyabraham** [comment]
Well, it would deliver the 2X size images to us on our retina machines which would look better right?

I agree it doesn't explain why WP re-size operation is worse than when I do the same operation with Preview.

**Comment by cjyabraham** [comment]
Basically, srcset is delivering images to my browser that should be double the pixel density.  Instead of delivering the 1536px one, it should at least deliver the 2560px one, if it wants to deliver the version of the image that can be made use of by the browser.  It seems the answer to this is to use the retina 2X designation to generate thumbnails to deliver to retina screens specifically.

**Comment by thetwopct** [comment]
My post above explains why the srcset is above 2048px is not being used, you need to edit a hook. 
Can you try disabling big_image_size_threshold as per recommendations?

**Comment by cjyabraham** [comment]
Unless I'm misunderstanding, I did not think your recommendations were relevant to this issue.  Whenever an image is too large, WP will scale it down to 2560px wide.  Since this is the exact size of 1 above, no scaling has occurred.  So we could disable it but it won't have any affect here.

When WP does scale down an image it appends "-scaled" like it has with [this one](https://pr-492-lfeventsci.pantheonsite.io/wp-content/uploads/2020/02/IMG_20200215_172535-scaled.jpg).  You'll see that it has scaled it down to 2560px wide.  I just uploaded it as a test (it was originally 4032px wide).

Your other recommendation about changing the compression setting of Shortpixel I also don't think is relevant.  The quality loss I'm most alarmed by is between 1 and 2, before Shortpixel has done anything.

Does that make sense?

**Comment by thetwopct** [comment]
Not really.

> The quality loss I'm most alarmed by is between 1 and 2, before ShortPixel has done anything.

So that would be an image size processed and generated via `big_image_size_threshold` so that's why disabling it would be my first port of call in resolving why processed images looked bad (if they look bad, which I don't agree with). Then I'd look at ShortPixel compression methods, as if they are a) using the already bad processed image or b) using the original image but processing them too strongly, then that would explain why images 3 & 4 look bad. That makes sense to me.

**Comment by cjyabraham** [comment]
I don't understand.  Disabling `big_image_size_threshold` just allows one to upload an image above 2560px.  [See this link](https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/).  None of the images in this test are above 2560px (1 is 2560px wide; 2 is 1526px wide) so it doesn't come in to play.  

Feel free to try it, however, and prove me wrong :)

**Comment by cjyabraham** [comment]
Regarding the apparent quality, it's not that they look bad, it's just that 1 looks significantly better than 2.  Before we were using srcset Megan could upload 1 and it would be the image that would appear on the site, so she's used to that level of quality.

**Comment by thetwopct** [comment]
Do you have a particular URL where I can check an image?

**Comment by cjyabraham** [comment]
Closing the loop on this...

This conversation was continued on Slack.  @thetwopct did some digging and discovered [a filter in FoundationPress](https://github.com/LF-Engineering/lfevents/blob/afa7574d9e82caecedbbaeff2c8ccda9d96057f4/web/wp-content/themes/lfevents/library/responsive-images.php#L47) that was providing the wrong "sizes" information to our srcset attributes that ended up delivering images that were smaller than they should be.  He wrote [a PR](https://github.com/LF-Engineering/lfevents/pull/493) to deactivate this filter, which has now been deployed.

If you look at the [Open Networking Summit site](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/) now, you'll see the text on image block, part way down, which is now delivering [this image](https://events.linuxfoundation.org/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-1-scaled-e1582062233900.jpg) to retina displays instead of [this one](https://events.linuxfoundation.org/wp-content/uploads/2020/02/48786592622_25ab3eb465_3k-1-scaled-e1582062233900-1536x588.jpg).  This effectively solves the original image quality problem Megan reported.
