### ISSUE TITLE
bullets not showing in editor

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#626]
When you edit [this post](https://events.linuxfoundation.org/2020/04/02/novel-coronavirus-update/) the bullets do not show in the editor although the do show on the front-end.  Can we make them show in the editor?

<img width="473" alt="Screen Shot 2021-01-13 at 10 02 33 AM" src="https://user-images.githubusercontent.com/463160/104396936-9c3aa600-5586-11eb-98ee-e87f70ba0e30.png">

**Comment by thetwopct** [comment]
The discs are there, but the way the editor is up to the edge of the menu prevents them from showing. 

![2021-01-15-125704@2x](https://user-images.githubusercontent.com/10615884/104730027-3d656000-5731-11eb-955f-4c342fa54494.jpg)

Have added some margin to the block, should be better.

**Comment by cjyabraham** [comment]
Why do the discs go outside of the left margin of the page in the editor?  Is it possible to keep them inside the page margin, as they are on the front-end?

**Comment by thetwopct** [comment]
On the frontend the content is in a container which we center, and the lists and other markup use that to position themselves. A list by default uses a 20px left margin to push itself away from the page container so that the list style discs can be displayed.

The editor markup is slightly different, there is no container, so we are centering all elements using `margin: auto`. The lists uses `margin-left: 20px;` to push themselves away from the edge of a page container, so `margin: auto` was overriding it, giving no space for the dots, and hence, they were off the screen until the screen (until the screen went wide enough the editor hit max-width)

**Comment by cjyabraham** [comment]
Can you fix this for numbered items as well?  On [this page](https://pr-630-lfeventsci.pantheonsite.io/dpdk-summit-apac/) the numbered items are appearing too far left on the front-end:
<img width="296" alt="Screen Shot 2021-01-18 at 10 14 47 AM" src="https://user-images.githubusercontent.com/463160/104865108-0e8bfb80-5976-11eb-9100-57140098bf04.png">

**Comment by thetwopct** [comment]
The example has gone with the PR I am afraid, and I'm not able to reproduce an issue for numbered items - the css I applied is already set for both `ul, ol.` 

![2021-01-19-094104@2x](https://user-images.githubusercontent.com/10615884/105016403-80c61400-5a3a-11eb-8121-bab79e6490f1.jpg)

**Comment by cjyabraham** [comment]
It only seems to be a problem on Event pages on the front-end.  [See this example](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/):
<img width="368" alt="Screen Shot 2021-01-19 at 5 47 20 PM" src="https://user-images.githubusercontent.com/463160/105017126-66ae2500-5a7e-11eb-982d-6a02661b7664.png">
